### ISSUE TITLE
symbol not found in flat namespace '_cass_batch_add_statement'

### ISSUE THREAD

**Issue by hitesh770** [acsylla/acsylla#83]
Hello i have used python 3.11.3 version on mac(M1) Although the installation is successfully , when i try to run my basic program
getting following error I am not sure what to do

hitesh.vishal@Hiteshs-MacBook-Pro sensors %  cd /Users/hitesh.vishal/Desktop/fastapi/sensors ; /usr/bin/env
 /Users/hitesh.vishal/.pyenv/versions/3.11.3/bin/python /Users/hitesh.vishal/.vscode/extensions/ms-python.p
ython-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 64916 -- -m main 
Traceback (most recent call last):
  File "/Users/hitesh.vishal/.pyenv/versions/3.11.3/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hitesh.vishal/.pyenv/versions/3.11.3/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/hitesh.vishal/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/hitesh.vishal/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/hitesh.vishal/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/Users/hitesh.vishal/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hitesh.vishal/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/hitesh.vishal/Desktop/fastapi/sensors/app/main.py", line 4, in <module>
    import acsylla
  File "/Users/hitesh.vishal/.pyenv/versions/3.11.3/lib/python3.11/site-packages/acsylla/__init__.py", line 1, in <module>
    from . import errors
  File "/Users/hitesh.vishal/.pyenv/versions/3.11.3/lib/python3.11/site-packages/acsylla/errors.py", line 1, in <module>
    from acsylla._cython.cyacsylla import AggregateNotFound
ImportError: dlopen(/Users/hitesh.vishal/.pyenv/versions/3.11.3/lib/python3.11/site-packages/acsylla/_cython/cyacsylla.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_cass_batch_add_statement'

@whiteluna @vangheem @dmanchon @pfreixes

**Comment by hitesh770** [comment]
I am not may be related to https://datastax.github.io/cpp-driver/topics/basics/batches/

**Comment by whiteluna** [comment]
посмотрю попозже

**Comment by whiteluna** [comment]
а ты можешь например дать свои вычислительные ресурсы?

**Comment by whiteluna** [comment]
этим мы и отличаемся, я это всё делал без задней мысли м мне за это никто не платил, мне просто было интересно)

**Comment by whiteluna** [comment]
идите нахуй все
